---
- name: run cli command pre hook
  include_tasks: "{{ eos_run_cli_command_pre_hook }}"
  when: eos_run_cli_command_pre_hook is defined and eos_run_cli_command_pre_hook

- name: run command and parse output
  cli:
    command: "{{ eos_command }}"
    parser: "{{ parser }}"
    engine: "{{ eos_parser_engine | default(None) }}"
  with_first_found:
    - files:
        - "{{ eos_parser }}"
      paths:
        - "{{ playbook_dir }}/parser_templates/eos"
        - "~/.ansible/ansible_network/parser_templates/eos"
        - "/etc/ansible/ansible_network/parser_templates/eos"
        - "{{ role_path }}/parser_templates"
  loop_control:
    loop_var: parser

- name: run cli command post hook
  include_tasks: "{{ eos_run_cli_command_post_hook }}"
  when: eos_run_cli_command_post_hook is defined and eos_run_cli_command_post_hook
