---
- name: config manager example
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  tasks:


  - name: push config files to cisco ios devices
    include_role:
      name: ansible-network.config_manager
      tasks_from: load.yaml
    vars:
      config_file: host_vars/{{ ansible_hostname}}
