---
- name: loop example
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  tasks:


  - name: collect facts from cisco ios devices
    import_role:
      name: ansible-network.cisco_ios
      tasks_from: get_config


  - debug: var=cisco_ios.config


  - name: configure on multiple interfaces
    ios_config:
      lines:
        - no switchport
      parents: "interface {{ item.value.name }}"
    with_dict: " {{ cisco_ios.config['interface-config'] }}"
