---
- name: parser example
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  tasks:


  - name: collect facts from cisco ios devices
    import_role:
      name: cisco_ios
      tasks_from: get_config

  - debug: var=cisco_ios.config

#  - name: collect facts from cisco ios devices
#    import_role:
#      name: cisco_ios
#      tasks_from: get_facts
#    vars:
#      subset:
#        - default
#        - interfaces
#        - prefix-list
#        - interface-config

#  - debug: var=cisco_ios.system
