---
- name: remove var example
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  tasks:


  - name: collect facts from cisco ios devices
    import_role:
      name: "{{ ansible_network_provider }}"
      tasks_from: get_config

  - debug: var=cisco_ios.config

  - name: "Remove unwanted name-servers"
    with_items: "{{ cisco_ios.config.value.ip_helper }}"
    when: "item not in dns_servers"
    ios_config:
      lines:
        - "no ip_helper {{ item }}"
      parents: "{{ cisco_ios.config.value }}"  
