---
- name: remove var example
  hosts: ios
  gather_facts: no
  connection: network_cli
  roles:
    - ansible-network.network-engine

  vars:
    ip_helper_template:
      - 10.10.10.10
      - 20.20.20.20

  tasks:


  - name: collect facts from cisco ios devices
    import_role:
      name: ansible-network.cisco_ios 
      tasks_from: get_config

  - debug: var=cisco_ios.config

  - name: "Remove unwanted ip helper addresses"
    with_dict: "{{ cisco_ios.config['interface-config'] }}"
    when: item.value.ip_helper | difference(ip_helper_template)
    set_fact:
      fix_dict: "{{ fix_dict | default([]) + [ { 'name': item.key, 'ips': item.value.ip_helper | difference(ip_helper_template) } ] }}"

  - name: iterate over new list
    with_subelements:
      - "{{ fix_dict }}"
      - ips
    ios_config:
      lines:
        - "no ip helper-address {{ item.1 }}"
      parents: "interface {{ item.0.name }}" 

