---

- name: ansible-network.network-engine
  src: https://github.com/mpetrive-rh/network-engine
  scm: git
  version: devel

- name: ansible-network.arista_eos
  src: https://github.com/ansible-network/arista_eos.git
  scm: git
  version: devel

- name: ansible-network.cisco_nxos
  src: https://github.com/ansible-network/cisco_nxos.git
  scm: git
  version: devel

- name: ansible-network.cisco_ios
  src: https://github.com/ansible-network/cisco_ios.git
  scm: git
  version: devel

- name: ansible-network.config_manager
  src: https://github.com/ansible-network/config_manager.git
  scm: git
  version: devel
