---
- name: validate role spec
  validate_role_spec:
    spec: load_config_spec.yaml

- name: invoke network provider
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: load_config
  when: ansible_network_provider is defined


