---
- name: parser meta data
  parser_metadata:
    version: 1.0
    command: show user-account
    network_os: eos

- name: match user sections
  pattern_match:
    regex: "user:.+"
    match_all: yes
    match_greedy: yes
  register: section

- name: match user values
  pattern_group:
    - name: match name
      pattern_match:
        regex: "user: (\\S+)"
        content: "{{ item }}"
      register: name
    
    - name: match role
      pattern_match:
        regex: "role: (\\S+)"
        content: "{{ item }}"
      register: role

    - name: match privilege
      pattern_match:
        regex: "privilege level: (\\d+)"
        content: "{{ item }}"
      register: privilege
   
    - name: match sshkey
      pattern_match:
        regex: "ssh public key: (.*)"
        content: "{{ item }}"
      register: sshkey

  loop: "{{ section }}"
  register: users

- name: generate json data structure
  json_template:
    template:
      - key: name
        value: "{{ item.name.matches.0 }}"
      - key: role
        value: "{{ item.role.matches.0 }}"
        when: item.role.matches.0 is defined
      - key: privilege
        value: "{{ item.privilege.matches.0 }}"
        when: item.privilege.matches.0 is defined
      - key: sshkey
        value: "{{ item.sshkey.matches.0 }}"
        when: item.sshkey.matches.0 is defined

  loop: "{{ users }}"
  export: yes
  register: user_account_facts
